x-common: &common
  logging:
    driver: "json-file"
    options:
      max-size: "500m"
      max-file: "5"
      compress: "true"
  restart: unless-stopped
  networks:
    - collabberry-frontend

services:
  frontend-app:
    <<: *common
    container_name: frontend-app
    build: .
    ports:
      - 4100:4100

networks:
  collabberry-frontend:
    driver: bridge
