x-common: &common
  logging:
    driver: "json-file"
    options:
      max-size: "500m"
      max-file: "5"
      compress: "true"
  restart: unless-stopped
  networks:
    - collabberry-frontend

services:
  frontend-app:
    <<: *common
    container_name: frontend-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_APP_BASE_URL=https://api.collabberry.xyz
        - VITE_APP_TEAM_POINTS_FACTORY_ADDRESS=0x69a99AeAc1F2410e82A84E08268b336116Ab3B5a
        - VITE_NODE_ENV=development
        - VITE_APP_URL=https://app.collabberry.xyz
        - VITE_APP_NETWORK=Arbitrum Sepolia
        - VITE_APP_BLOCK_EXPLORER=https://sepolia.arbiscan.io/tx
        - VITE_APP_TEAM_POINTS_FACTORY_ADDRESS_CELO="0x0e414560fdEeC039c4636b9392176ddc938b182D"
    image: collabberry/frontend-app:latest

networks:
  collabberry-frontend:
    driver: bridge
